config/routes.rb
Integra::Application.routes.draw do
  resources :organizations

  resources :deals do
    resources :items
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  #every item is linked to a deal, through deal_id
  belongs_to :deal
end

app/controllers/items_controller.rb
require 'net/http'
require 'json'

class ItemsController < ApplicationController
  before_filter :get_deal
  # :get_deal is defined at the bottom of the file, 
  # and takes the deal_id given by the routing and
  # converts it to an @student object.
  
  # GET /items
  # GET /items.json
  def index
    @items = @deal.items

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = @deal.items.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @deal = Deal.find(params[:deal_id])    

    token_pipedrive = "api_token=57f839e9a500cf2ef6b9dc8b156bce2c09a0905d"
    uri_pipedrive_prod = "http://api.pipedrive.com/v1/deals/#{@deal.pipedrive_id}/products?start=0&#{token_pipedrive}"

    respprod = Net::HTTP.get_response(URI.parse(uri_pipedrive_prod))
    parsedprod = JSON.parse(respprod.body)

    parsedprod["data"].each do |registro|
      @item = @deal.items.build
      @item.unique_id = registro["id"]
      @item.pipe_deal_id = registro["deal_id"]
      @item.order_nr = registro["order_nr"]
      @item.product_id = registro["product_id"]
      @item.item_price = registro["item_price"]
      @item.sum = registro["sum"]
      @item.currency = registro["currency"]
      @item.name = registro["name"]
      @item.quantity = registro["quantity"]

      uritpprod = "http://api.pipedrive.com/v1/products/#{registro["product_id"]}?#{token_pipedrive}"
      resptpprod = Net::HTTP.get_response(URI.parse(uritpprod))
      parsedtpprod = JSON.parse(resptpprod.body)
    
      @item.product_code = parsedtpprod["data"]["code"]
      @item.save
    end

    redirect_to :action => :index

    #respond_to do |format|
    #  format.html # new.html.erb
    #  format.json { render json: @item }
    #end
  end

  # GET /items/1/edit
  def edit
    @item = @deal.items.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = @deal.items.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to deal_items_url(@deal), notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = @deal.items.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to deal_items_url(@deal), notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = @deal.items.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to (deal_items_path(@deal)) }
      format.json { head :no_content }
    end
  end

  private
  # get_deal converts the deal_id given by the routing
  # into an @deal object, for use here and in the view.
  def get_deal
    @deal = Deal.find(params[:deal_id])
  end
  
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for([@deal, @item]) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :unique_id %><br />
    <%= f.number_field :unique_id %>
  </div>
  <div class="field">
    <%= f.label :pipe_deal_id %><br />
    <%= f.number_field :pipe_deal_id %>
  </div>
  <div class="field">
    <%= f.label :order_nr %><br />
    <%= f.number_field :order_nr %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :item_price %><br />
    <%= f.text_field :item_price %>
  </div>
  <div class="field">
    <%= f.label :sum %><br />
    <%= f.text_field :sum %>
  </div>
  <div class="field">
    <%= f.label :currency %><br />
    <%= f.text_field :currency %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :product_code %><br />
    <%= f.text_field :product_code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item do deal <%= @deal.pipedrive_id %></h1>

<%= render 'form' %>

<%= link_to 'Show', [@deal, @item] %> |
<%= link_to 'Back', deal_items_path(@deal) %>

app/views/items/index.html.erb
<h1>Items para Deal <%= @deal.pipedrive_id %></h1>

<% if !@deal.items.empty? %>
  <table>
    <tr>
      <th>Unique</th>
      <th>Pipe deal</th>
      <th>Order nr</th>
      <th>Product</th>
      <th>Item price</th>
      <th>Sum</th>
      <th>Currency</th>
      <th>Name</th>
      <th>Quantity</th>
      <th>Product code</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

<% @items.each do |item| %>
  <tr>
    <td><%= item.unique_id %></td>
    <td><%= item.pipe_deal_id %></td>
    <td><%= item.order_nr %></td>
    <td><%= item.product_id %></td>
    <td><%= item.item_price %></td>
    <td><%= item.sum %></td>
    <td><%= item.currency %></td>
    <td><%= item.name %></td>
    <td><%= item.quantity %></td>
    <td><%= item.product_code %></td>
    <td><%= link_to 'Show', [@deal, item] %></td>
    <td><%= link_to 'Edit', edit_deal_item_path(@deal, item) %></td>
    <td><%= link_to 'Destroy', [@deal, item], :confirm => 'Voce tem certeza?',
:method => :delete %></td>
  </tr>
<% end %>
</table>

<br />
<% else %>
  <p><%= @deal.pipedrive_id %> nao possui nenhum produto ainda.</p>
<% end %>
<p>
<%= link_to 'New item', new_deal_item_path(@deal) %> |
<%= link_to 'Back', @deal %>
</p>

app/views/items/new.html.erb
<h1>New item para deal <%= @deal.pipedrive_id %></h1>

<%= render 'form' %>

<%= link_to 'Back', deal_items_path(@deal) %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Unique:</b>
  <%= @item.unique_id %>
</p>

<p>
  <b>Pipe deal:</b>
  <%= @item.pipe_deal_id %>
</p>

<p>
  <b>Order nr:</b>
  <%= @item.order_nr %>
</p>

<p>
  <b>Product:</b>
  <%= @item.product_id %>
</p>

<p>
  <b>Item price:</b>
  <%= @item.item_price %>
</p>

<p>
  <b>Sum:</b>
  <%= @item.sum %>
</p>

<p>
  <b>Currency:</b>
  <%= @item.currency %>
</p>

<p>
  <b>Name:</b>
  <%= @item.name %>
</p>

<p>
  <b>Quantity:</b>
  <%= @item.quantity %>
</p>

<p>
  <b>Product code:</b>
  <%= @item.product_code %>
</p>


<%= link_to 'Edit', edit_deal_item_path(@deal, @item) %> |
<%= link_to 'Back', deal_items_path %>