config/routes.rb
Integra::Application.routes.draw do
  resources :organizations

  resources :deals do
    resources :items
  end

end

app/models/organization.rb
class Organization < ActiveRecord::Base
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pipedrive_id %><br />
    <%= f.number_field :pipedrive_id %>
  </div>
  <div class="field">
    <%= f.label :my_finance_id %><br />
    <%= f.number_field :my_finance_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :segmento %><br />
    <%= f.text_field :segmento %>
  </div>
  <div class="field">
    <%= f.label :razao_social %><br />
    <%= f.text_field :razao_social %>
  </div>
  <div class="field">
    <%= f.label :fisica_juridica %><br />
    <%= f.number_field :fisica_juridica %>
  </div>
  <div class="field">
    <%= f.label :cpf_cnpj %><br />
    <%= f.text_field :cpf_cnpj %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :update_time %><br />
    <%= f.datetime_select :update_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing organization</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<h1>Listing organizations</h1>

<table>
  <tr>
    <th>Pipedrive</th>
    <th>My finance</th>
    <th>Name</th>
    <th>Segmento</th>
    <th>Razao social</th>
    <th>Fisica juridica</th>
    <th>Cpf cnpj</th>
    <th>Url</th>
    <th>Email</th>
    <th>Update time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @organizations.each do |organization| %>
  <tr>
    <td><%= organization.pipedrive_id %></td>
    <td><%= organization.my_finance_id %></td>
    <td><%= organization.name %></td>
    <td><%= organization.segmento %></td>
    <td><%= organization.razao_social %></td>
    <td><%= organization.fisica_juridica %></td>
    <td><%= organization.cpf_cnpj %></td>
    <td><%= organization.url %></td>
    <td><%= organization.email %></td>
    <td><%= organization.update_time %></td>
    <td><%= link_to 'Show', organization %></td>
    <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
    <td><%= link_to 'Destroy', organization, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Organization', new_organization_path %>

app/views/organizations/new.html.erb
<h1>New organization</h1>

<%= render 'form' %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Pipedrive:</b>
  <%= @organization.pipedrive_id %>
</p>

<p>
  <b>My finance:</b>
  <%= @organization.my_finance_id %>
</p>

<p>
  <b>Name:</b>
  <%= @organization.name %>
</p>

<p>
  <b>Segmento:</b>
  <%= @organization.segmento %>
</p>

<p>
  <b>Razao social:</b>
  <%= @organization.razao_social %>
</p>

<p>
  <b>Fisica juridica:</b>
  <%= @organization.fisica_juridica %>
</p>

<p>
  <b>Cpf cnpj:</b>
  <%= @organization.cpf_cnpj %>
</p>

<p>
  <b>Url:</b>
  <%= @organization.url %>
</p>

<p>
  <b>Email:</b>
  <%= @organization.email %>
</p>

<p>
  <b>Update time:</b>
  <%= @organization.update_time %>
</p>


<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>